# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Starting step
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} step
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: npm ci step
        run: npm ci

      - name: npm run step
        run: npm run build --if-present

      - name: Create .env file step
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          envkey_AWS_REGION: ${{ secrets.AWS_REGION }}
          envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_HOST: ${{ secrets.HOST }}
          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
          envkey_PASSWORD: ${{ secrets.PASSWORD }}
          envkey_REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          envkey_USERNAME: ${{ secrets.USERNAME }}
          directory: home/ubuntu/app_backend/\_work/backend_auth_pictures_aws/backend_auth_pictures_aws
          file_name: .env
          fail_on_empty: false
      - name: Restart PM2 step
        run: sudo pm2 restart app_backend_process
